server:
  port: 80
spring:
  config:
    activate:
      on-profile: dev
open:
  api:
    title: ${API_TITLE:}
    api-docs: api-service
    version: v1.0.0
    description: Mota API service
    serverUrl: http://localhost:${server.port}
    serverName: server dev