spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/my_db}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
#  sql:
#    init:
#      mode: always
#      schema-locations: classpath:initdb.sql
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: Asia/Ho_Chi_Minh
    show-sql: true
    hibernate:
      ddl-auto: none
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:29092}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    from: tdemoch0712@gmail.com
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
open:
  api:
    title: ${API_TITLE:}
    api-docs: api-service
    version: v1.0.0
    description: Mota API service
    serverUrl: http://localhost:${server.port}
    serverName: server dev